### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by bumbar1** [edgurgel/poxa#104]
Trying to build on Ubuntu 16.04:

* Elixir 1.5.2: 

```** (Mix) Could not compile dependency :erlware_commons, "/home/prog1/.mix/rebar3 bare compile --paths "/home/prog1/git/libs/poxa/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile erlware_commons", update it with "mix deps.update erlware_commons" or clean it with "mix deps.clean erlware_commons"```

* Elixir 1.2.6: 

```
** (Version.InvalidRequirementError) ~> 1.0
    (elixir) lib/version.ex:133: Version.match?/2
    (mix) lib/mix/local.ex:68: Mix.Local.check_elixir_version_in_ebin/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/local.ex:21: Mix.Local.append_archives/0
    (mix) lib/mix/cli.ex:8: Mix.CLI.main/1
```

Cleaning or updating `erlware_commons` doesn't help.

**Comment by edgurgel** [comment]
Yeah we need to update to the newest elixir and update some deps

**Comment by edgurgel** [comment]
I just updated master with Elixir 1.5 + Erlang 20. I need to fix some stuff but soon a new release is coming 👍
