### ISSUE TITLE
SSL issue on starting Poxa

### ISSUE THREAD

**Issue by GH0STL1N3R** [edgurgel/poxa#109]
Hi all,

I freshly installed poxa on my machine and when run the command: `sudo elixir -pa _build/dev/consolidated -S mix run --config my_config.exs --no-halt` it hangs on  `[info]  Starting Poxa using SSL on port 8443`

I tried to disable ssl, but then it keeps hanging on `[info]  SSL not configured/started`

Am I doing something wrong or what could this be?

**Comment by edgurgel** [comment]
are you using master? And what's inside your `config.exs`?
