### ISSUE TITLE
How to set up the config file for version 0.7 (as a release)

### ISSUE THREAD

**Issue by 1x24** [edgurgel/poxa#110]
I couldn't get the v0.6 release to work with Elixir 1.6 and Erlang 20, so I cloned the Poxa repo, downloaded dependencies and generated the release. Finally I was going to run it as a daemon, but I needed to set up the config and there was no "releases" folder.

I found a config folder instead, and this had 4 files: config.exs, poxa.dev.conf poxa.prod.conf and poxa.schema.exs.

Some of those files had similar settings in them, and I am not sure which ones take precedence. Am I meant to copy the poxa.dev.conf file to poxa.conf and then fill out the config details? Or just use the poxa.dev.conf file directly.

Thanks

**Comment by edgurgel** [comment]
Hey! Recently I did some refactor on the way we publish releases and the README.md is not 100% done. I should be able to finish this weekend and finally release a new version. 

The release directory is now inside `_build` and yeah the conf is now per environment. You can find some generic docs here: https://hexdocs.pm/distillery/getting-started.html and here: https://hexdocs.pm/conform/getting-started.html

Sorry for the confusion!

**Comment by 1x24** [comment]
Great! I figured the docs were outdated but I tried to wing it anyway. I have checked out the links about Hex but I couldn't figure out what I needed to change, by myself as I'm pretty new to it. I will wait for the weekend release, then. Thank you.

**Comment by edgurgel** [comment]
Cool I just updated the README with more info. Can you check if it's enough? My last step is fixing the docker build part. It's almost 100% but I still may need to do some tweaks. Then finally release 0.7.0

**Comment by 1x24** [comment]
Hey Eduardo, thanks for all your help! I wanted to keep trying before I reached out again. No luck, sadly. I will just wait for the 0.7.0 release when you can get round to it.

**Comment by edgurgel** [comment]
Oh sorry for the slow feedback. I plan to move this forward this week. It seems to be working locally perfectly. I will review once again the README.md and probably release later this week

**Comment by 1x24** [comment]
Thank you, Eduardo!

**Comment by edgurgel** [comment]
Ok so if you are building yourself, the file that you should change is:

`_build/prod/rel/poxa/releases/0.7.0/poxa.conf`

to generate a release:

`MIX_ENV=prod mix release`

You could also use the docker image to run using docker.
