### ISSUE TITLE
ETA on http://poxa.herokuapp.com/ coming back online?

### ISSUE THREAD

**Issue by binary64** [edgurgel/poxa#111]
Hi,
Would you be able to re-instantiate http://poxa.herokuapp.com/ for us please?
It would help a great deal
Thanks

**Comment by edgurgel** [comment]
Yeah I'm struggling with it :(. 

I'm trying to run the docker container as part of Heroku but I'm failing to find what's the issue. It works locally but I not when it runs on Heroku. If someone knows more about Heroku and Docker feel free to try with the last automated docker built: https://hub.docker.com/r/edgurgel/poxa-automated/tags/

To run locally: `docker pull edgurgel/poxa-automated:latest`

**Comment by binary64** [comment]
How about try https://zeit.co/now instead, it might be suitable for this.

**Comment by edgurgel** [comment]
Finally got it right! It's online now!
