### ISSUE TITLE
Validation (?) error on sending socket_id

### ISSUE THREAD

**Issue by reignmaker** [edgurgel/poxa#116]
Hello,
i have a problem with sending socket_id in API request.

```
[9] pry(main)> Pusher.trigger('my-channel', 'my-event', {message: 'test1'}, socket_id: '123123')

Pusher::Error: Bad request: {"error":"Event must have channel(s), name, and data"}
from /home/sonar/.rvm/gems/ruby-2.4.0@dev/gems/pusher-1.3.1/lib/pusher/request.rb:90:in `handle_response'
```
Sending this request to pusher.com returns no errors and the console shows socket_id as well.

![image](https://user-images.githubusercontent.com/1104764/36075322-34c0c57a-0f5e-11e8-8a3b-339a5ca5adcc.png)

Am i missing something?

Thanks.

**Comment by edgurgel** [comment]
This socket_id is not a valid socket_id for Poxa: https://github.com/edgurgel/poxa/commit/e965fff2357553f5e2cf65a008af7ac8964712e6

Poxa won't generate such `socket_id`
