### ISSUE TITLE
Cluster error cannot find app_key

### ISSUE THREAD

**Issue by top1st** [edgurgel/poxa#120]
`funds-24c429bb06c2cc08964f6807d916bcc08ee29a72944c49ff892c6e2242ff5240.js:14481 Pusher : Error : {"type":"PusherError","data":{"code":4001,"message":"Did you forget to specify the cluster when creating the Pusher instance?  App key app_key does not exist in this cluster."}}`

I have installed poxa and used defualt config
poxa config there is not option cluster.
Could you check what is this problem?
And could you show me exactly running demo code that you showed in description.
The source code and real running site don't have equal code.

**Comment by cvoege** [comment]
Is there any fix for this?

**Comment by cvoege** [comment]
@edgurgel

**Comment by edgurgel** [comment]
I dont know how to replicate this issue

**Comment by heitorpolidoro** [comment]
Having this issue.

In JS
```
    const pusher = new Pusher('app_key', {
      app_id: 'app_id',
      port: 8080,
      host: 'localhost',
      secret: 'secret'
    });
```
