### ISSUE TITLE
Why pusher javascript client can not subscribe when application is running on localhost.

### ISSUE THREAD

**Issue by vetal20600** [edgurgel/poxa#121]
I have Rails application and I want to us posa. I think it's beautiful software
However I am having issues using Posa and I am trying to figure out why it happened.
When I try to put settings in my Rails application which allow to connect to http://poxa.herokuapp.com/ it shows me next log:
![screen shot 2018-04-21 at 03 17 26](https://user-images.githubusercontent.com/4103746/39078439-017984fa-4513-11e8-95b6-ebff482b0c6f.png)
As you see there are no API Messages above.
But when I am deploy and run release version on localhost  I see no subscription from clients (I see only API Messages).
![screen shot 2018-04-21 at 03 32 44](https://user-images.githubusercontent.com/4103746/39078622-b69c616c-4514-11e8-866c-33d49d710e4a.png)

I am not sure what is reason. (May be it is not even Posa related)

**Comment by vetal20600** [comment]
Ok what I know now. For some reason javascript pusher client works (connect/subscribe and so one) if I put:

```
Host: http://poxa.herokuapp.com
App key: "app_key"
App id: "app_id"
App secret: "secret"
Port: 80
```

but my Rails application does not produce any api messages.
At the same time if I run on localhost, it produces messages but pusher javascript client does not work. Can't figure out what happens. Maybe this is server security related so I have to check router and open some ports?

**Comment by vetal20600** [comment]
I am trying to connect Posa with [peatio](github.com/peatio/peatio) which uses Pusher service by default.
One more thing. 
That software connected with your instance of Posa (poxa.herokuapp.com) and deployed on server with dedicated IP works as expected. 
However same software deployed on server which is put in router does not generates API Messages, only javascript pusher client works.

**Comment by satish-blockchain** [comment]
Did anyone get this working?

I am facing the same problem with some domains. When I point the same docker to a different domain it works.
Not sure what it has to do with the domain. Can someone point out what might be wrong?

**Comment by edgurgel** [comment]
It may be related to this https://github.com/edgurgel/poxa/issues/154 ? We may need to enforce cowboy to expose 0.0.0.0 instead of localhost? 🤔
