### ISSUE TITLE
Server process crash on attempt to send notification

### ISSUE THREAD

**Issue by Dian8** [edgurgel/poxa#127]
Poxa server log:

07:46:16.797 [error] GenServer #PID<0.991.0> terminating
** (ArgumentError) argument error
    (kernel) gen_tcp.erl:149: :gen_tcp.connect/4
    (hackney) /source/deps/hackney/src/hackney_connect.erl:246: :hackney_connect.do_connect/5
    (hackney) /source/deps/hackney/src/hackney_connect.erl:37: :hackney_connect.connect/5
    (hackney) /source/deps/hackney/src/hackney.erl:315: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:439: HTTPoison.Base.request/9
    (poxa) lib/poxa/web_hook/dispatcher.ex:43: Poxa.WebHook.Dispatcher.send_web_hook!/1
    (poxa) lib/poxa/web_hook/dispatcher.ex:25: Poxa.WebHook.Dispatcher.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
Last message: :timeout
State: nil

=CRASH REPORT==== 19-Jun-2018::07:46:16 ===
  crasher:
    initial call: Elixir.Poxa.WebHook.Dispatcher:init/1
    pid: <0.991.0>
    registered_name: []
    exception exit: badarg
      in function  gen_tcp:connect/4 (gen_tcp.erl, line 149)
      in call from hackney_connect:do_connect/5 (/source/deps/hackney/src/hackney_connect.erl, line 246)
      in call from hackney_connect:connect/5 (/source/deps/hackney/src/hackney_connect.erl, line 37)
      in call from hackney:request/5 (/source/deps/hackney/src/hackney.erl, line 315)
      in call from 'Elixir.HTTPoison.Base':request/9 (lib/httpoison/base.ex, line 439)
      in call from 'Elixir.Poxa.WebHook.Dispatcher':'send_web_hook!'/1 (lib/poxa/web_hook/dispatcher.ex, line 43)
      in call from 'Elixir.Poxa.WebHook.Dispatcher':handle_info/2 (lib/poxa/web_hook/dispatcher.ex, line 25)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
    ancestors: [<0.962.0>,<0.959.0>,<0.855.0>]
    message_queue_len: 0
    messages: []
    links: [<0.962.0>,<0.830.0>]
    dictionary: [{#Ref<0.3919228715.3884974083.96209>,
                   {client,undefined,
                           {metrics_ng,metrics_dummy},
                           hackney_tcp,[],80,<<>>,[],nil,nil,
                           #Ref<0.3919228715.3884974083.96209>,true,
                           hackney_pool,5000,false,5,false,5,nil,nil,nil,
                           {0,
                            {dict,0,16,16,8,80,48,
                                  {[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                   [],[]},
                                  {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                    [],[]}}}},
                           undefined,start,nil,normal,false,false,false,
                           undefined,false,nil,waiting,nil,4096,<<>>,[],
                           undefined,nil,nil,nil,nil,undefined,nil}}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 14051
  neighbours:

=SUPERVISOR REPORT==== 19-Jun-2018::07:46:16 ===
     Supervisor: {<0.962.0>,'Elixir.Poxa.WebHook.Supervisor'}
     Context:    child_terminated
     Reason:     badarg
     Offender:   [{pid,<0.991.0>},
                  {id,'Elixir.Poxa.WebHook.Dispatcher'},
                  {mfargs,{'Elixir.Poxa.WebHook.Dispatcher',start_link,[]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]

**Comment by edgurgel** [comment]
Hey, thanks for the report! 

Have you configured webhooks? 🤔 

Can you explain exactly what have you done to get this error? Thanks!

**Comment by Dian8** [comment]
I've just tried to get poxa up and running using pre-built docker image
  edgurgel/poxa-automated:latest
and php composer package 
  "pusher/pusher-php-server": "^3.0.4",

No web hooks were configured

I had a client connected and notification sent from php. After I've found notification not delivered and server with original log.
Reproducibility is not 100% so I don't know exactly which action caused crash

**Comment by edgurgel** [comment]
Ok it seems to be the case that it's trying to send a webhook because of the default config. I'm going to release a new version with a fix! Thanks for the bug report once again!

**Comment by edgurgel** [comment]
https://github.com/edgurgel/poxa/releases/tag/v0.7.4
