### ISSUE TITLE
Problem with using POXA

### ISSUE THREAD

**Issue by ow-grant** [edgurgel/poxa#132]
Hello there, poxa is great, but i have a problem with using it.; 
my ruby appliaction was writeen to use pusher and it works ok with it, but i have too many messages, 
i'm trying to user Poxa, there is API messages in console, but no subscirbtions or anything else. 
I was running debugger on pusher and compared messages -they are equal.

Maybe i need to setup poxa.web_hook?
But i have no idea what should be there

Could you help me with that?

**Comment by edgurgel** [comment]
so there are 2 steps for using Pusher/Poxa. The javascript/client side and the server side. You need to ensure that both are talking to Poxa.

Have you followed these instructions here https://github.com/edgurgel/poxa#your-application ?
