### ISSUE TITLE
Enable SSL with AWS ElasticBeanstalk

### ISSUE THREAD

**Issue by gus4no** [edgurgel/poxa#134]
Hello, so I've managed to run poxa console behind https just fine but wss doesn't seem to work. And I'm reaching out to see if you can help somehow. :)

By looking at the logs, I noticed that 

`13:18:25.292 [info]  SSL not configured/started`

because I need to pass some extra options not just `:enabled` I also need to pass `:certfile` and `:keyfile`. 

Is there a way I can leave this to EB balancers?  Or do I really need to have access to the certs?

**Comment by edgurgel** [comment]
AFAIK Amazon load balancers can deal with this for you as long as you provide the certificate to the load balancer. It will do the "proxying" as if Poxa could speak SSL.

**Comment by gus4no** [comment]
mmmm... then it must be something else, because I can't even log into poxa console from https all I get is 400 errors. 

Thanks for the quick reply :)

**Comment by gus4no** [comment]
Turns out it was bad configuration in EB load balancers. Sorry :sweat_smile:
