### ISSUE TITLE
Docker run stuck

### ISSUE THREAD

**Issue by huynt57** [edgurgel/poxa#143]
Thanks for creating an awesome app
I have a question

When I run:

```
sudo docker run -d --name poxa -e PORT=8080 -e POXA_SSL=true -e SSL_PORT=8081 -e POXA_APP_KEY='itro' -e POXA_SECRET='itro@2018' -e POXA_APP_ID='123' -e SSL_CERTFILE='/etc/letsencrypt/live/poxa.itro.vn/fullchain.pem' -e SSL_KEYFILE='/etc/letsencrypt/live/poxa.itro.vn/privkey.pem' edgurgel/poxa-automated:latest

```

my log stuck at:

```
11:47:27.509 [info]  Starting Poxa, app_id: 123 on port 8080

11:47:27.510 [info]  Starting Poxa using SSL on port 8081

```
and poxa didn't start. What did I do wrong ? Thank you.

**Comment by edgurgel** [comment]
Hey @huynt57 ,

I think you are missing the port exposure from docker? so you need to change to :

`docker run -d --name poxa -p 8080:8080 -p 8081:8081 ....`

So that 8080 is exposed outside of the container and 8081 as well. You can always remap them to different ports like 80, 433, etc.

**Comment by huynt57** [comment]
I changed my command as you said, but nothing changed. My docker logs still hang on there.

**Comment by edgurgel** [comment]
I see. What happens when you do `curl -i localhost:8080` for exameple? Do you get any response?

**Comment by huynt57** [comment]
I got "Connection refused".
I also check and make sure there are no restriction on ports.
