### ISSUE TITLE
Getting issue in connecting with locally hosted poxa

### ISSUE THREAD

**Issue by AnkitRathore175** [edgurgel/poxa#144]
Hi,
i have configured this on my localhost and trying to connect with https://github.com/pusher-community/pusher-presence-dem app with below config in pusher_init.rb-
```
# Get some free Pusher credential for development use:
Pusher.app_id = '1234'
Pusher.key    = 'app_key'
Pusher.secret = 'secret'

# not strictly necessary, but referenced in views
PUSHER_JS_DOMAIN = 'https://js.pusher.com'
PUSHER_SOCKET_HOST = 'localhost'
PUSHER_WS_PORT = 8080
```

And below config in config.exs:-
```
import Config
if Mix.env == :test do
  config :logger, backends: []
end

import System
config :poxa,
  port: get_env("PORT", "8080") |> String.to_integer(),
  app_key: get_env("POXA_APP_KEY", "app_key"),
  app_secret: get_env("POXA_SECRET", "secret"),
  app_id: get_env("POXA_APP_ID", "1234"),
  registry_adapter: get_env("POXA_REGISTRY_ADAPTER", "gproc"),
  web_hook: get_env("WEB_HOOK", nil),
  payload_limit: get_env("PAYLOAD_LIMIT") || 10_000

config :poxa, :ssl,
  enabled: get_env("POXA_SSL", "false") == "true",
  port: get_env("SSL_PORT", "8443") |> String.to_integer(),
  cacertfile: get_env("SSL_CACERTFILE", ""),
  certfile: get_env("SSL_CERTFILE", ""),
  keyfile: get_env("SSL_KEYFILE", "")
```

After this configurations i m getting below response in app
![image](https://user-images.githubusercontent.com/38749604/65249586-d8383500-db11-11e9-9a0a-0cd9c0c74222.png)

Please help me to find what di i missed
Thanks in advance

**Comment by edgurgel** [comment]
Hey @AnkitRathore175, this ruby project is really really old. I would suggest you to upgrade the dependencies first or use some other example app.

**Comment by AnkitRathore175** [comment]
Hi @edgurgel 
yes i resolved it, i was not using correct config, 
However i wanted to know why i m able to use any numbers for app_id?
thanks
