### ISSUE TITLE
How to run poxa in local

### ISSUE THREAD

**Issue by guru260** [edgurgel/poxa#145]
I have installed poxa using [this instruction](https://gist.github.com/rubencaro/6a28138a40e629b06470) After that I have cloned poxa.
```
git clone https://github.com/edgurgel/poxa.git
mix deps.get
mix compile
```
How to run poxa? From the [docker file](https://hub.docker.com/r/edgurgel/poxa-automated/dockerfile) I thought it would be `_build/prod/rel/poxa start` But in my local I can not find such path. I have like `_build/dev` I can not rel or poxa directory. How to run poxa in my local machine.

**Comment by edgurgel** [comment]
Hey @guru260 , you need to call `mix release` to generate a release: https://github.com/edgurgel/poxa/blob/master/Dockerfile#L24

If you want to run the development version without a release you can run `iex -S mix` which will open a console with the app open.
