### ISSUE TITLE
where is poxa.conf and how do i change host to 0.0.0.0?

### ISSUE THREAD

**Issue by whatsdis** [edgurgel/poxa#154]
I cannot find where the default poxa.conf file is, where does it need to be, what are the formats?

I need to change the host from localhost to 0.0.0.0 which is running on a webserver and I need to access it via 234.234.234:8080 for example.

**Comment by edgurgel** [comment]
Poxa.conf is not used since 1.0.0. Every configuration is exposed by environment variables:  https://github.com/edgurgel/poxa#configuration
