### ISSUE TITLE
1 minute disconnects

### ISSUE THREAD

**Issue by tgmweb** [edgurgel/poxa#156]
Sorry for raising another ticket so quickly, but I've nearly got everything working. However, I'm getting exactly (well, within 5 second) reliable 1 minute disconnects.

I'm using pusher-js, and poxa is running on a m4 AWS instance with hardly anything running. I have poxa running on port 8080 and I'm connecting directly, not through a proxy like nginx. I do have nginx running on the same server - and I'm running pushstream nginx module, which I'm also connecting to over web sockets. Pushstream doesn't have the 1 minute issue. However, even if I terminate nginx it makes no difference to poxa.

It doesn't matter if the connection is idle or active - disconnects are reliably one minute.

![image](https://user-images.githubusercontent.com/821589/69778172-47c64280-119b-11ea-8f22-1a92d5d044ef.png)

If I switch the wsHost back to pusher server I don't get this issue. I've tried upping the ENV variable ACTIVITY_TIMEOUT to a silly number - it doesn't make any difference, and as I said, this is reliable even when the socket is active and receiving messages. 

I've also tried in both Firefox and Chrome, and the issue is the same.

Any idea?

**Comment by tgmweb** [comment]
Just to update - I get the same 1 minute disconnects on https://poxa.herokuapp.com, so I don't think this is anything to do with my poxa setup. Also, it doesn't look like the herokuapp uses pusher-js, so that's not the issue either.

![image](https://user-images.githubusercontent.com/821589/69818203-2776a200-11f4-11ea-91f1-481fc77ef1d0.png)

**Comment by tgmweb** [comment]
Update 3 - I get the same issue on https://poxa.herokuapp.com using my cellphone connected to 4G - which takes my PC, local network and everything else out of the equation. 

After approx 1 minute I get booted and it asks for the app_key and secret again, despite there being activity over the socket.

**Comment by edgurgel** [comment]
interesting... Thanks for the detailed report. I will investigate this weekend 👍

**Comment by edgurgel** [comment]
Version 1.1.1 is out!
