### ISSUE TITLE
How to use poxa without docker with multiple configurations on Ubuntu?

### ISSUE THREAD

**Issue by NevaJava** [edgurgel/poxa#162]
Hello,

i've updated my poxa installation on ubuntu from 0.6 to 1.0.0 last night. After i started my both apps i realized that i got the following error.

```
warning: the --config flag is deprecated. If you need to handle multiple configurations, it is preferrable to dynamically import them in your config files
```
`screen -dmS app1 elixir -pa _build/dev/consolidated -S mix run --config config/app1.exs --no-halt`
`screen -dmS app2 elixir -pa _build/dev/consolidated -S mix run --config config/app2.exs --no-halt`

How to use and handle now multiple configurations? Didn't understand exactly how to use enviroments variables etc.

Greetings

**Comment by edgurgel** [comment]
Hi @NevaJava,

I suggest looking at the Dockerfile to see how you can run Poxa:

https://github.com/edgurgel/poxa/blob/09ff93db97f6d533fd2b7211557990f375401fc3/Dockerfile#L38

Running

`MIX_ENV=prod mix release` then  you can run the app inside

`_build/prod/rel/poxa start`

All configurations must be done through environment variables. So no config file can be loaded.
