### ISSUE TITLE
Distributed server example?

### ISSUE THREAD

**Issue by aemadrid** [edgurgel/poxa#18]
I see it as a todo item but wonder if it is possible now but it is not documented?

**Comment by manishval** [comment]
Hi @edgurgel, any update on this?

**Comment by edgurgel** [comment]
Hey @manishval, I have a PR with the implementation here: https://github.com/edgurgel/poxa/pull/26
My main problem is how to set it up. It's not as simple as I want, but it's totally functional.

I want to play with it soon. I want to make it dead simple to set up a cluster and that's no the case right now.

**Comment by manishval** [comment]
Thanks @edgurgel
