### ISSUE TITLE
Http fallbacks if websocket not supported

### ISSUE THREAD

**Issue by snewcomer** [edgurgel/poxa#186]
Hi!  I'm trying to determine if poxa supports fallback to http (long polling for example).  I know Cowboy has Channels which support this feature.  But perusing the code or documentation, I'm not sure I can confidently make the same conclusion here.  

Have folks here discussed this or happen to know the answer?  If it takes a bit more wrangling, I would be happy to do any work in this area.

**Comment by edgurgel** [comment]
Sorry for the super late reply! Nope we only support websockets at the moment. I
