### ISSUE TITLE
Question: Client ping causing error in poxa?

### ISSUE THREAD

**Issue by doogie99** [edgurgel/poxa#34]
Hi,

Poxa seems to be working well for me except for when the keep-alive ping is being sent from two different .NET based clients (PusherClient and JDI.Pusher) that I'm using. Here is a sample error message being kicked out by poxa:

15:43:46.601 [error] Ranch listener :http had connection process started with :cowboy_protocol:start_link/4 at #PID<0.351.0> exit with reason: {[reason: :function_clause, mfa: {Poxa.WebsocketHandler, :websocket_handle, 3}, stacktrace: [{Poxa.WebsocketHandler, :websocket_handle, [{:ping, "2015-07-03 3:43:46 PM"}, {:http_req, #Port<0.6037>, :ranch_tcp, :keepalive, #PID<0.351.0>, "GET", :"HTTP/1.1", {{127, 0, 0, 1}, 56437}, "localhost", :undefined, 8081, "/app/7D45B688CA9841BE898E", :undefined, "protocol=5&client=pusher-dotnet-client&version=0.0.1", [{"protocol", "5"}, {"client", "pusher-dotnet-client"}, {"version", "0.0.1"}], [app_key: "7D45B688CA9841BE898E"], [{"upgrade", "WebSocket"}, {"connection", "Upgrade"},
 {"sec-websocket-version", "13"}, {"sec-websocket-key", "ZjJkNDI2YWYtMWU1MS00OA=="}, {"host", "localhost:8081"}, {"origin", "ws://localhost:8081"}], [{"upgrade", ["websocket"]}, {"connection", ["upgrade"]}], :undefined, [websocket_version:13, websocket_compress: false], :waiting, "", :undefined, false, :done, [], "", :undefined}, %Poxa.WebsocketHandler.State{socket_id: "2705428123.152006606", time: 1435959766}], [file: 'lib/poxa/websocket_handler.ex', line: 72]}, {:cowboy_websocket, :handler_call, 7, [file: 'src/cowboy_websocket.erl', line: 588]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 435]}], msg: {:ping, "2015-07-03 3:43:46 PM"}, req: [socket: #Port<0.6037>, transport: :ranch_tcp, connection: :keepalive, pid: #PID<0.351.0>, method: "GET", version: :"HTTP/1.1", peer: {{127, 0, 0, 1}, 56437}, host: "localhost", host_info: :undefined, port: 8081, path: "/app/7D45B688CA9841BE898E", path_info: :undefined, qs: "protocol=5&client=pusher-dotnet-client&version=0.0.1", qs_vals: [{"protocol", "5"}, {"client", "pusher-dotnet-client"}, {"version", "0.0.1"}], bindings: [app_key: "7D45B688CA9841BE898E"], headers: [{"upgrade", "WebSocket"}, {"connection", "Upgrade"}, {"sec-websocket-version", "13"}, {"sec-websocket-key", "ZjJkNDI2YWYtMWU1MS00OA=="}, {"host", "localhost:8081"}, {"
origin", "ws://localhost:8081"}], p_headers: [{"upgrade", ["websocket"]}, {"connection", ["upgrade"]}], cookies: :undefined, meta: [websocket_version: 13, websocket_compress: false], body_state: :waiting, buffer: "", multipart: :undefined, resp_compress: false, resp_state: :done, resp_headers: [], resp_body: "", onresponse: :undefined], state: %Poxa.WebsocketHandler.State{socket_id: "2705428123.152006606", time: 1435959766}], [{:cowboy_protocol, :execute, 4, [file: 'src/cowbo
y_protocol.erl', line: 435]}]}

I'm not sure whether the issue is on the client or server side or even really how to interpret what is going on here. I've looked around for support somewhere else to no avail. Is there anything obvious in this apparent stacktrace as to what the problem is?

Thanks,

Doug

**Comment by edgurgel** [comment]
Oh, hey @doogie99 this seems to be a missing clause for the websocket handler. I will patch it tomorrow! It's a really simple fix :+1: 

Thanks for the report. As soon as I fix this I will release a new version.

**Comment by edgurgel** [comment]
This [commit](https://github.com/edgurgel/poxa/commit/d42b25fe1c5830b2ca6c3a9c850f81aca333a494) should fix this. I just released a new version (0.4.1) with this bugfix.

Thanks for the report. Feel free to close the issue if it works for you.

**Comment by doogie99** [comment]
That solved the problem. Thanks for the fix!
