### ISSUE TITLE
SSL setup on release version

### ISSUE THREAD

**Issue by funsterisdafunniest** [edgurgel/poxa#35]
Hi, is there any way to enable ssl on the release version?
I can't seem to find it on the readme

**Comment by darrencauthon** [comment]
I use SSL with Poxa, works just fine.  It's about halfway through the readme, with the following sample code:

```elixir
use Mix.Config

config :poxa,
  port: 4567,
  app_key: "123456789",
  app_secret: "987654321",
  app_id: "theid",
  ssl: [port: 8443,
        cacertfile: "priv/ssl/server-ca.crt",
        certfile: "priv/ssl/server.crt",
        keyfile: "priv/ssl/server.key"]
```

**Comment by funsterisdafunniest** [comment]
@darrencauthon  thanks, but that was for the build/dev version
i'm planning to use the release version which use different settings file (in the documentation, it's just below the line that you referred to)

**Comment by edgurgel** [comment]
@funsterisdafunniest, I just releases a new version with the missing configuration for releases:

https://github.com/edgurgel/poxa/releases/tag/v0.4.2

I will update the README.md soon with instructions but the example `config/poxa.conf` should be enough to use it.

I tested with custom certificates. If you find any issues please report back! Thanks for opening the issue.

**Comment by funsterisdafunniest** [comment]
@edgurgel thanks! i'll try it as soon as i get my hands on my development machine
