### ISSUE TITLE
Getting "erlexec: HOME must be set" error when trying to run with supervisord

### ISSUE THREAD

**Issue by ludo-h** [edgurgel/poxa#36]
I'm trying to run poxa with supervisord, because for some reason occasionally poxa will just die after a few weeks.

When I run it from the cli it just works.
But when running it through supervisord, it will output: 
"/home/ludohelder/poxa/rel/poxa/bin/poxa: 79: /home/ludohelder/poxa/rel/poxa/bin/poxa: /erts-6.4/bin/escript: not founderlexec: HOME must be set"

This is my supervisord conf file
```
[program:poxa]
process_name=poxa_supervisord
command=/home/ludohelder/poxa/rel/poxa/bin/poxa start
autostart=true
autorestart=true
numprocs=1
environment=HOME="/home/ludohelder"
```

I actually added the last line recently, to try to fix the "HOME must be set error" but it doesn't work.

**Comment by edgurgel** [comment]
Hey thanks for the bug report. I will take a look soon! 

Strange that it takes weeks to raise this error Oo

**Comment by edgurgel** [comment]
Could you please share which Linux distro and which version you are using so I can try to replicate the problem? Using supervisord on OS X seems to work just fine.

Also you mentioned that poxa was dying after a few weeks. I would love to know more about as it could be some misconfiguration with the release generated by `exrm`.

**Comment by edgurgel** [comment]
Also I noticed you are using `poxa start`. I think you should use `poxa foreground` as supervisord expects that your application will not "daemonize". http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses

**Comment by edgurgel** [comment]
Ping?

**Comment by ludo-h** [comment]
I've tried the foreground, but also didn't work.

**Comment by ludo-h** [comment]
I'm running it on: Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-44-generic x86_64)

**Comment by edgurgel** [comment]
Reading again I noticed this message: "bin/escript: not found" 

Are you sure that erlang is installed on this machine?

Could you run this `erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell` ?

It should output something like 

```
$ erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
"18"
```

**Comment by ludo-h** [comment]
yes, it is installed. I can run poxa when I just manually run it from the cli.
But I would like supervisord to keep it running, since for some reason it stops running every 3-4 weeks.

This is the output of the erlang:
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [kernel-poll:false]
"17"

**Comment by edgurgel** [comment]
My guess is that supervisord does not have access to erlang PATH or something like this. Can try to run supervisord passing -n  (so supervisord will run on your terminal and output) just this command above `erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell` ? 

I ran supervisord with Poxa on the same ubuntu version that you specified and I didn't have any issues :/

**Comment by gerep** [comment]
Take a look at this answer:

http://stackoverflow.com/a/19611920/745235
