### ISSUE TITLE
Docker pull edgurgel/poxa dont work

### ISSUE THREAD

**Issue by arrowcircle** [edgurgel/poxa#40]
Hi!
If you try to use regular docker syntax to pull image you get error

```
> docker pull edgurgel/poxa
Using default tag: latest
Pulling repository docker.io/edgurgel/poxa
Tag latest not found in repository docker.io/edgurgel/poxa
```

Could you please add tag latest to 0.4.2 image?

**Comment by edgurgel** [comment]
Sure! Thanks for the report! :+1:

**Comment by edgurgel** [comment]
Done: https://hub.docker.com/r/edgurgel/poxa/tags/
