### ISSUE TITLE
The docker run command suggested in the readme don't work

### ISSUE THREAD

**Issue by RobertoSchneiders** [edgurgel/poxa#46]
The [readme](https://github.com/edgurgel/poxa#using-docker) suggests this command:
```
docker run --rm -p 8080:8080 -v $PWD/mypoxa.conf:/app/releases/0.4.2/poxa.conf edgurgel/poxa:0.4.2
```

For me, this ends up in this error:
```
Cannot start container d8a46ec73d1578c9cb3888b2a1011b2da28d122b9d24bbcd7394b17a0f518e41: [8] System error: not a directory
```

AFAIK, the `-v` option is used to mount directories, not files. ([Docker Run Command Line reference](https://docs.docker.com/reference/commandline/run/)).

I have no experience with docker, so, I'm unable to make this works with `run` command. Some references that I found says that we have to use the `cp` command.  The easy way I found to make this work was create my own image with a dockerfile like this:
```
FROM edgurgel/poxa:0.4.3

ADD ./poxa.conf /app/releases/0.4.3/poxa.conf

EXPOSE 80
```
as explained [here](https://github.com/RobertoSchneiders/poxa/tree/elasticbeanstalk_deploy_instructions#deploying-on-elasticbeanstalk)

I am using Docker version 1.8.1, build d12ea79

**Comment by bsedat** [comment]
It was a little confusing but I got a directory error when it could not find the local file to link to the container.

**Comment by RobertoSchneiders** [comment]
@bsedat I think this occurs because docker is looking for a directory, not a file.

**Comment by edgurgel** [comment]
The -v option mounts files as well: https://docs.docker.com/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume

That example is supposing you have "mypoxa.conf" on the working directory. Can you check if that's the case?

**Comment by RobertoSchneiders** [comment]
Yes, I have. 

Sorry, I had not seen this part of the `-v` documentation. I'll do some more tests.

**Comment by bsedat** [comment]
When I ran into this before my issue was that the config file had to exist on the docker server host.

**Comment by RobertoSchneiders** [comment]
I make some more tests today and it's working perfectly. This was obviously my mistake. 

I'm not sure what I did wrong in the first time. Probably some confusion with the name of the file :grimacing:. I noticed that some of my tests I made without `$PWD`, which don't work. 

Sorry for bothering you. 

Thank you
