### ISSUE TITLE
Why public events are not published?

### ISSUE THREAD

**Issue by RobertoSchneiders** [edgurgel/poxa#48]
I'm trying to use public channels and I can't find a way to broadcast the messages. I see that messages for public channels are not being published ([code](https://github.com/edgurgel/poxa/blob/d42b25fe1c5830b2ca6c3a9c850f81aca333a494/lib/poxa/websocket_handler.ex#L104)).

I have to use private or presence channels? The .NET client library has a complicated authentication mechanism for this channels, I'm trying to avoid it.

**Comment by edgurgel** [comment]
You mean client-events https://pusher.com/docs/client_api_guide/client_events#trigger-events ?

Client events are just for private/presence channels. From the docs:

> Client events can only be triggered on private and presence channels because they require authentication

A normal event is triggered through the `/events` REST API. I suggest you to read this https://pusher.com/docs/server_api_guide/interact_rest_api . After a quick search through pusher organisation I think you should use this: https://github.com/pusher/pusher-http-dotnet

**Comment by RobertoSchneiders** [comment]
Thanks for clarifying.

The problem with this library is that it does not use websocket, so, I'll have to use two different libraries, one for sending messages and one for receiving. I wish I could avoid it.

**Comment by edgurgel** [comment]
I see.. but that's how Pusher works. You can use client-events as they are generated through the websocket connection but they require private/presence channels.

More info: https://pusher.com/docs

![documentation___pusher_-_vimperator](https://cloud.githubusercontent.com/assets/30873/9863073/0f29e266-5b91-11e5-8309-df4e11d33870.png)

**Comment by RobertoSchneiders** [comment]
Yeah, of course. I didn't mean to say it was your problem, I was just thinking out loud, sorry. 

Thank you

**Comment by edgurgel** [comment]
Haha. I'm sorry if it felt like I was complaining :)

no problem! :+1: 

It's important to have authentication here as it would be fairly easy to spam your system using a public channel.
