### ISSUE TITLE
Changing App Key and App Secret does not work 

### ISSUE THREAD

**Issue by hrishiballal** [edgurgel/poxa#49]
I am new to this project. 

I forked the repository, changed the poxa.conf with a new created app_id, app_key and secret and deployed it on Heroku. The new app_key, secret does not work on the new server and the interface. However, the default variables work, even though poxa.conf was changed. 

What am I missing? Would appreciate any guidance.

**Comment by edgurgel** [comment]
I should change the README to clarify that the buildpack for Heroku does not use the `exrm` release so you need to either change `config/config.exs` or simply set the environment variables:

```
PORT=8080
POXA_APP_KEY=app_key
POXA_SECRET=secret
POXA_APP_ID=app_id
```

Using `heroku config:set` should be enough to achieve this.

Can you check if this works for you?

**Comment by hrishiballal** [comment]
Thanks will check tomorrow.

**Comment by hrishiballal** [comment]
Confirmed it works, thanks for this.

**Comment by edgurgel** [comment]
Awesome :+1:
