### ISSUE TITLE
Crypto.app error when using 'mix deps.get'

### ISSUE THREAD

**Issue by gerep** [edgurgel/poxa#51]
Poxa: `v0.4.3`
Elixir: `1.0.0`
Erlang: `17.0`

Running `mix deps.get`

```
{"init terminating in do_boot",{{badmatch,{error,{crypto,{"no such file or directory","crypto.app"}}}},[{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,56}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

Is that an Elixir error?

**Comment by gerep** [comment]
As I was expecting, it was a problem with Erlang not being compiled with openssl.

In case someone here faces the same situation....

When installing Erlang it is required to configure it with ssl and be sure to have the `development openss` package installed.

**Comment by darrencauthon** [comment]
Thank you for the note on the resolution... notes like that on closed issues have saved me a lot of time. :smile:

**Comment by edgurgel** [comment]
Thanks for sharing! :+1:
