### ISSUE TITLE
Warning about latin1 encoding while using UTF-8

### ISSUE THREAD

**Issue by gerep** [edgurgel/poxa#53]
When running poxa from my upstart script I get this warning:

```
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
```

Running `locale` I get this:

```
LANG=en_US.utf-8
LC_CTYPE="en_US.utf-8"
LC_NUMERIC="en_US.utf-8"
LC_TIME="en_US.utf-8"
LC_COLLATE="en_US.utf-8"
LC_MONETARY="en_US.utf-8"
LC_MESSAGES="en_US.utf-8"
LC_PAPER="en_US.utf-8"
LC_NAME="en_US.utf-8"
LC_ADDRESS="en_US.utf-8"
LC_TELEPHONE="en_US.utf-8"
LC_MEASUREMENT="en_US.utf-8"
LC_IDENTIFICATION="en_US.utf-8"
LC_ALL=
```

Is there anywhere else I can configure it? Am I doing something wrong?

**Comment by darrencauthon** [comment]
Do you get the same warning if you run Poxa without upstart?

**Comment by gerep** [comment]
@darrencauthon No, just when using upstart

**Comment by edgurgel** [comment]
Oh hey! Can you share your upstart script or a small script so I can test myself? And also can you give me the Erlang version you are using? Cheers!

**Comment by gerep** [comment]
@edgurgel  of course and sorry for not doing that when opening this issue

Erlang: `Erlang/OTP 18 [erts-7.0] [source] [64-bit]`


```
# Upstart Configuration
# put on /etc/init
description     "Poxa"
author          "CloudWalk"

start on (filesystem or runlevel [2345])
stop on runlevel [!2345]

console none

pre-start script
    test -x /home/ec2-user/poxa/rel/poxa/bin/poxa || { stop; exit 0; }
    exec >"/tmp/$UPSTART_JOB.env"
end script

script
        export HOME=/home/ec2-user
        cd $HOME/poxa
        . "/tmp/$UPSTART_JOB.env"
        echo "[`date -u +%Y-%m-%dT%T.%3NZ`] Starting..." >> /var/log/poxa.log 2>&1
        exec ./rel/poxa/bin/poxa start >> /var/log/poxa.log 2>&1
end script
```

Check the log at `/var/log/poxa.log` to see the Warning message

**Comment by gerep** [comment]
Change my upstart script to call `foreground` and the same error happens

**Comment by edgurgel** [comment]
Thanks for the info. I will take a look at this during the weekend. Sorry for the massive delay to reply.

**Comment by edgurgel** [comment]
Does it fix if you do `env LANG=en_US.UTF-8` in your file?
