### ISSUE TITLE
Redis integration

### ISSUE THREAD

**Issue by Slamper** [edgurgel/poxa#55]
Do you plan to integrate Redis to store "session" data (persistence etc.) to allow horizontal scaling of poxa ?

**Comment by edgurgel** [comment]
Why Redis would be necessary to scale Poxa? 

We use `gproc` as our process registry (which stores "session" data) and we have a working branch for distributed Poxa: https://github.com/edgurgel/poxa/pull/26

It needs a little bit more of work but it's mostly working. I just didn't have free time to invest :)

**Comment by Slamper** [comment]
Ok nice. I didn't know that it was capable to do this on it's own across multiple hosts :) I'm looking forward to seeing the working distributed poxa system. Great work !

**Comment by edgurgel** [comment]
Hopefully I will push the multiple apps support forward and then focus on distributed Poxa :+1: Stay tuned! :)

**Comment by iwanbk** [comment]
:+1:
