### ISSUE TITLE
Got strange 4001 error

### ISSUE THREAD

**Issue by arrowcircle** [edgurgel/poxa#58]
Today I tested Pusher 3.0 JS client with Poxa on Chrome on Mac and got strange error:
![pusher_error](https://cloud.githubusercontent.com/assets/171336/12330093/6dbb0b76-baf4-11e5-8f50-8186db1cd159.png)
It uses app_id, app_key and app_secret eq to '1'.
My colleague also had same problem on Chrome on Mac. It works in Safari. It works in Chrome on Windows.
I tried to disable encryption in js client, but ring no bells. I run pusher in docker, that is then proxied over nginx to the world.
I switched to official pusher server and problem has gone.
I think problem can be with missing responses to pusher servers.
One of them is routes like "/timeline*" for stats.
Also, as I remember, pusher sometimes send server list to connect.
I still investigating the problem.

@edgurgel Did You ever had this problem?

**Comment by edgurgel** [comment]
I never had this problem. Can you replicate running locally or only when you use proxied over nginx?

**Comment by arrowcircle** [comment]
@edgurgel I tried to run poxa locally, but cant catch same problem.

Poxa is running in docker, on port 8089, here is nginx config:

```
upstream push {
  server 127.0.0.1:8089;
}

server {
    listen 80;
    server_name my_pusher_url;
    proxy_intercept_errors on;

    location / {
        proxy_pass http://push;
        proxy_redirect off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

**Comment by edgurgel** [comment]
Yeah it's ok to run only on Elixir 1.0.0. I also didn't manage to replicate. It seems to be related to nginx proxy?

**Comment by arrowcircle** [comment]
@edgurgel The problem was with old nginx. After update I never get this error.

**Comment by edgurgel** [comment]
Good to know! Thanks for the report!
