### ISSUE TITLE
Invalid signature: Expected HMAC SHA256 hex digest of ...

### ISSUE THREAD

**Issue by PhillippOhlandt** [edgurgel/poxa#83]
Hey,

we started Poxa via Docker with its default config. When I try to subscribe to a private channel, I get the following error:

```
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Invalid signature: Expected HMAC SHA256 hex digest of 151004717.3505838415:private-test, but got {\"auth\":\"app_key:ceb4d48b4403ee6bc48eef122af7c9c847fc1a6abbc26996fb10ccd1ad97dc7a\"}"}}}
```

I am not sure what is causing the problem. I am using version `v2.4.1` of the pusher php server lib and `3.1` of the javascript lib.

My code to return the auth key is the following:

```
$pusher = new \Pusher('app_key', 'secret', 'app_id', [], 'our host', 8080);
    	$key = $pusher->socket_auth($request->get('channel_name'), $request->get('socket_id'));
    	return new JsonResponse(['auth' => $key], 200);
```

Everything looks fine.

**Comment by PhillippOhlandt** [comment]
Ok, seems like I just have to return the key as plain text.

**Comment by PhillippOhlandt** [comment]
Yeah, the pusher php lib already gives me a json string. Everything works fine now :) Just ignore this, its friday :)

**Comment by edgurgel** [comment]
All good! Good to know that it is working 👍
