### ISSUE TITLE
ELB proxy protocol support

### ISSUE THREAD

**Issue by matthewford** [edgurgel/poxa#86]
Hi,

I'm having issues running this behind an ELB with SSL and proxy protocol enabled. 

I'm not sure if this will help, but looks like the issue:

https://github.com/ninenines/cowboy/issues/708

They mention this repo could help: 

https://github.com/heroku/ranch_proxy_protocol

**Comment by matthewford** [comment]
Ended up not using proxy protocol and just using tls

**Comment by edgurgel** [comment]
Oh cool! 👍 Thanks for the info
