### ISSUE TITLE
Network error connecting to pusher (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by subhashsaran** [edgurgel/poxa#87]
I set it up poxa is running successfully on port 8080. Here are logs for same
```

11:36:46.304 [info]  Subscribing to channel live_chat_1c9994304e093170958293b1378481a3_proj_id_1

11:36:46.304 [info]  Registering #PID<0.515.0> to channel live_chat_1c9994304e093170958293b1378481a3_proj_id_1

11:36:46.473 [info]  Registering #PID<0.515.0> to channel presence-chat-a49c5686fca263cfeb61540daa49608b

11:36:46.474 [info]  Subscribing to channel private-typingIndicator1c9994304e093170958293b1378481a3_proj_id_1development

11:36:46.474 [info]  Registering #PID<0.515.0> to channel private-typingIndicator1c9994304e093170958293b1378481a3_proj_id_1development
```
But it's not transmitting messages to and fro. either channels are not binding properly or something. Pushe is giving me this error. `Network error connecting to pusher (Errno::ECONNREFUSED)`

**Comment by edgurgel** [comment]
How can I replicate this issue? I'm having no issues to connect with Poxa.

**Comment by subhashsaran** [comment]
This issues is solved, I was specifying wrong port in Configuration. We are currently using Slanger which is Ruby based with Pusher and it's not doing very well for us and we are Considering Elixir our Next option and Poxa would be a good migration option for us. is poxa compatiable with HaProxy which we are currently using on production to communicate with Slanger? Please advise on how do we set it up on Production.

**Comment by edgurgel** [comment]
I can't see why it wouldn't work. I never tried to work with HaProxy and Poxa. I already used Amazon ELBs with Poxa and it worked fairly well.

I'm closing this issue as it's clear that it was just misconfigured.
