### ISSUE TITLE
Does it have the same 10kb limit as Pusher does?

### ISSUE THREAD

**Issue by TheRusskiy** [edgurgel/poxa#91]

**Comment by edgurgel** [comment]
Yes it does! https://github.com/edgurgel/poxa/blob/d0d68bcd652b611676448cdff279a3660c6227e4/test/event_handler_test.exs#L79-L87

**Comment by TheRusskiy** [comment]
As far as I understand Pusher has it to limit client's ability to send unlimited data, but if it's self hosted, does it really make sense to have this limit? Make it optional at least?
@edgurgel

**Comment by edgurgel** [comment]
Yes, It is there to protect servers so that they don't get overloaded. I would accept a PR to make it configurable through `Application env` (config.exs). Then users could simple say: my limit is 1 GB, etc
