### ISSUE TITLE
Error with SSL Option

### ISSUE THREAD

**Issue by Revyn112** [edgurgel/poxa#92]
Hello,

i tried to start poxa with a SSL Port, but i get the following error:
`Transport option {:enabled, true} unknown or invalid.` 

This is my config:

```
use Mix.Config

config :poxa,
  port: 8080,
  app_key: "123456789",
  app_secret: "987654321",
  app_id: "1",

  ssl: [enabled: true,
        port: 8443,
        cacertfile: "priv/ssl/server-ca.crt",
        certfile: "priv/ssl/server.crt",
        keyfile: "priv/ssl/server.key"]
```

Also non-ssl connections working perfectly.

**Comment by edgurgel** [comment]
Thanks for the bug report. I will investigate later today.

**Comment by edgurgel** [comment]
Cool I've found the issue! Thanks for the report. I will release a version soon with this change.
