### ISSUE TITLE
Enum.uniq/2 is deprecated

### ISSUE THREAD

**Issue by mhmd1983** [edgurgel/poxa#96]
Hello,
I get this error in console every time an event triggered 
`warning: Enum.uniq/2 is deprecated, use Enum.uniq_by/2 instead
  (elixir) lib/enum.ex:2547: Enum.uniq/2
  (poxa) lib/poxa/presence_subscription.ex:40: Poxa.PresenceSubscription.subscribe!/2
  (poxa) lib/poxa/websocket_handler.ex:83: Poxa.WebsocketHandler.handle_pusher_event/4
  (cowboy) src/cowboy_websocket.erl:588: :cowboy_websocket.handler_call/7
  (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
`
linux debian Jessie 64
Erlang/OTP 19
elixir version 1.4.1
any ideas ?

**Comment by edgurgel** [comment]
Thanks for the report! it should be pretty easy to replace it by `uniq_by`

**Comment by edgurgel** [comment]
Removed on master!
