### ISSUE TITLE
Multiple nodes, high availability

### ISSUE THREAD

**Issue by michaeltcoelho** [edgurgel/poxa#97]
Hi there,

are you guys using poxa on production? if so how do you guys handle high availability? How do you guys run poxa on 2 or 3 instances? I've got a tight deadline for a chat application and the way we planned our design is to have a cluster of pubsub servers exchanging messages and hooking up our chat microservice for each message for storaging.

**Comment by edgurgel** [comment]
Hey! The distributed part of Poxa is still part of the TODO: https://github.com/edgurgel/poxa#todo

Happy to accept PRs :)
