### ISSUE TITLE
Is there anyone using Poxa on production?

### ISSUE THREAD

**Issue by michaeltcoelho** [edgurgel/poxa#98]
Hi there,

i'd like o know if is there anyone using Poxa on production. What issues or benefits are you having by using poxa?

Thanks.

**Comment by edgurgel** [comment]
Another one from the README: https://github.com/edgurgel/poxa#who-is-using-it

**Comment by darrencauthon** [comment]
@michaeltcoelho  I've used Poxa in production for a long time.  

It was one of those applications that just worked.... I can't think of any problems I've ever had with it.

Now, just to be clear -- I didn't exactly tax it, as I was using it to maintain connections with a handful of multiple users at a time, and the messages I sent were very simple.  But it just worked out great, and this is one of my favorite projects.

**Comment by edgurgel** [comment]
@darrencauthon , it's always good to read this kind of comment. Thanks for sharing :)
