### ISSUE TITLE
Error on custom config

### ISSUE THREAD

**Issue by JacobJohansen** [edgurgel/poxa#99]
Hello, I keep getting this error when using a custom config through a docker volume, using the default config also causes the issue

` copying /app/poxa/releases/0.6.0/poxa.conf to /app/poxa/running-config/poxa.conf ...
pusher_1               | using /app/poxa/running-config/poxa.conf to populate "/app/poxa/running-config".
pusher_1               | ** (CaseClauseError) no case clause matching: {:error, :eisdir}
pusher_1               |     (conform) lib/conform/parse.ex:34: Conform.Parse.file/1
pusher_1               |     (conform) lib/conform/conf.ex:17: Conform.Conf.from_file/1
pusher_1               |     (conform) lib/conform.ex:78: Conform.process/1
pusher_1               |     (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
`

any suggestions would be greatly appreciated

**Comment by edgurgel** [comment]
could you share how you are running (with docker run ...) ?

**Comment by JacobJohansen** [comment]
im currently running it through docker compose

`pusher:
    image: edgurgel/poxa-automated:latest
    ports:
      - '8080:8080'
      - '8443:8443'
    expose:
      - '8080'
      - '8443'
    volumes:
      - .pusherssh/ssl.key:/priv/ssl/ssl.key
      - .pusherssh/ssl.cer:/priv/ssl/ssl.cer
      - .pusherssh/ca.cer:/priv/ssl/ca.cer
      - .pusherssh/poxa.conf2.txt:/app/poxa/running-config/poxa.conf
    restart: unless-stopped`

**Comment by edgurgel** [comment]
Config files will be removed on the next version. Just environment variables will be supported
